# .github/workflows/create_html.yml
name: Create and Commit HTML

on:
  workflow_dispatch: # هذا يسمح بتشغيل السير عمل يدويًا من واجهة GitHub
    inputs:
      filename:
        description: 'اسم ملف HTML (مثال: index.html)'
        required: true
        default: 'index.html'
      content:
        description: 'محتوى ملف HTML'
        required: true
        default: '<!DOCTYPE html><html><head><title>My Page</title></head><body><h1>Hello GitHub Actions!</h1></body></html>'
      commit_message:
        description: 'رسالة الالتزام (Commit Message)'
        required: true
        default: 'Add/Update HTML file via GitHub Actions'
      branch_name:
        description: 'اسم الفرع للرفع إليه (مثال: main)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # هذا السطر مهم جداً للسماح للعملية بالرفع إلى نفس المستودع
          # يستخدم الرمز الذي تم تكوينه في الخطوة 4
          token: ${{ secrets.GH_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any for Python script)
        run: |
          python -m pip install --upgrade pip
          # إذا كان سكريبت Python يحتاج إلى مكتبات إضافية، ضعها هنا
          # pip install requests

      - name: Run Python script to create and commit file
        env:
          # تمرير الرمز كمتغير بيئة آمن للسكريبت
          TOKEN: ${{ secrets.GH_TOKEN }} 
          # GITHUB_REPOSITORY يتم توفيره تلقائيًا بواسطة GitHub Actions (owner/repo)
        run: |
          python create_and_commit.py \
            "${{ github.event.inputs.filename }}" \
            "${{ github.event.inputs.content }}" \
            "${{ github.event.inputs.commit_message }}" \
            "${{ github.event.inputs.branch_name }}"